name: 1 Deploy Resource Group

on: workflow_dispatch

env:
  AZURE_RG: RG-POC-BICEPS-CPS
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_REGION: eastus2
  TAG_01CeCo: TEST

jobs:
  deploy-bicep-template:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Create Azure RG
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az group create --location ${{ env.AZURE_REGION }} --name ${{ env.AZURE_RG }}  --tags 01CeCo=${{ env.TAG_01CeCo }}
