name: 0 Validate Credentials

on: workflow_dispatch

env:
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_REGION: eastus2

jobs:
  validate-azure-credentials:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
