name: 0 Validate Credentials

on: workflow_dispatch

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_REGION: eastus2

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-secret: "aGy8Q~72HGLWRlQOdYnk7EY7UmdYBikq~dcH_ccM"
          client-id: "23b43c36-f72f-49a1-884e-6f9283a32194"
          tenant-id: "7094d542-3815-4c82-b1d5-6917d0443cf4"
          subscription-id: "15b4ecde-73be-4ed2-958c-4fee3ed9df0c"

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
